projects:
  1pitch:
    schemaPath: graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: 'C:/Projekte/1Pitch/graphql'
        maxDepth: 2
extensions:
  amplify:
    version: 3
